#!/bin/bash

for f in ./*.c; do
  gcc "$f"
  ./a.out
  echo "$f"
  read -p "Press any key to resume..." -n1 -s
done

for f in ./*.py; do
  python3 -m doctest "$f"
  echo "$f"
  read -p "Press any key to resume..." -n1 -s
done
