#!/bin/bash

for f in *.c; do
  if [ -f "$f" ]; then
    gcc "$f"
    ./a.out
    echo "$f"
    read -p "Press any key to resume..." -n1 -s
  fi
done

for f in ./*.py; do
  if [ -f "$f" ]; then
    python3 -m doctest "$f"
    echo "$f"
    read -p "Press any key to resume..." -n1 -s
  fi
done
